services:
  postgres:
    image: 'postgres:alpine'
    environment:
      - 'POSTGRES_DB=springboot_students'
      - 'POSTGRES_PASSWORD=Melon@123'
      - 'POSTGRES_USER=root'
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - '5432'
