services:
  postgres:
    image: 'postgres:alpine'
    environment:
      - POSTGRES_DB=springboot_students
      - POSTGRES_PASSWORD=Melon@123
      - POSTGRES_USER=root
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - spring-project

  app:
    build:
      context: .
    container_name: spring-app
    ports:
      - '8080:8080'
    networks:
      - spring-project
    depends_on:
      - postgres

networks:
  spring-project:
    driver: bridge
