services:
  postgres:
    image: 'postgres:alpine'
    environment:
      - POSTGRES_DB=springboot_students
      - POSTGRES_PASSWORD=Melon@123
      - POSTGRES_USER=root
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - spring-project

  app:
    build:
      context: .
    container_name: spring-app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/springboot_students
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Melon@123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - '8080:8080'
      - '8009:8009'
    networks:
      - spring-project
    depends_on:
      - postgres

networks:
  spring-project:
    driver: bridge
